# Generated by Django 6.0.5 on 2026-06-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='Profissional',
            new_name='profissional',
        ),
    ]
